when:
  - event: [push, pull_request, manual]

steps:
  - name: install
    image: node:22-alpine
    commands:
      - npm ci

  - name: test
    image: node:22-alpine
    commands:
      - npm test

  - name: build
    image: node:22-alpine
    commands:
      - npm run build
